addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.4.10")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.1.5")
//addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "1.6.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
